# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180917_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='callId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Call'),
        ),
    ]
