# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-17 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180917_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='callId',
        ),
    ]
