# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_file_callid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='callId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.Call'),
            preserve_default=False,
        ),
    ]
